package assertions;

import api.todos.Todos;

/**
 * {@link Todos} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractTodosAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class TodosAssert extends AbstractTodosAssert<TodosAssert, Todos> {

  /**
   * Creates a new <code>{@link TodosAssert}</code> to make assertions on actual Todos.
   * @param actual the Todos we want to make assertions on.
   */
  public TodosAssert(Todos actual) {
    super(actual, TodosAssert.class);
  }

  /**
   * An entry point for TodosAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myTodos)</code> and get specific assertion with code completion.
   * @param actual the Todos we want to make assertions on.
   * @return a new <code>{@link TodosAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static TodosAssert assertThat(Todos actual) {
    return new TodosAssert(actual);
  }
}
